train: []
inference:
  - _target_: src.metrics.CERMetric
    name: "CER_${decode.mode}"
    text_encoder: ${text_encoder}
    mode: ${decode.mode}
  - _target_: src.metrics.WERMetric
    name: "WER_${decode.mode}"
    text_encoder: ${text_encoder}
    mode: ${decode.mode}
